spring:
  h2:
    console:
      enabled: true # H2 ?? ????
      path: /h2-console # H2 ??? ??? ??, ???? 8080???? localhost:8080/h2-console? ?????? ?? ?? ??

  datasource:
    url: jdbc:h2:~/test; # ???? ???? H2DB? ???? ?? ??
    driver-class-name: org.h2.Driver # datasource driver? h2? ??
    hikari:
      username: admin # H2DB ???? ??
      password: # H2DB ???? ????, ???? ? ???? ?? ??? ??

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect # ?? ???? JPA?? DB ?? ??? ??? ????? ??
    hibernate:
      ddl-auto: create # ???? ????? ???? ?? ???? ?? ?? ? ???
    show-sql: true # ?? ??? ?? ??? ??? ? ??? ?? ??